lnk_signIn = '(//a[contains(text(),"Sign In")])[1]'
txt_box_usrname='//input[@name="login[username]"]'
txt_box_password='//input[@name="login[password]"]'
btn_login='//button[@class="action login primary"]'
home_page_of_luman='//span[@class="logged-in"]'
menu_xpath='//span[contains(text(),<menu_option>)]'
selection_page='//span[contains(text(),<selection>)][@class="base"]'
item_list='//a[@class="product-item-link"][contains(text(),<item>)]'
item_headder='//span[@class="base"][contains(text(),<item>)]'
item_size='//div[@class="swatch-option text"][@option-label="XS"]'
item_size_selected='//div[@class="swatch-option text selected"][@option-label="XS"]'
item_color='//div[@class="swatch-option color"][@option-label="Blue"]'
item_color_selected='//div[@class="swatch-option color selected"][@option-label="Blue"]'
add_to_cart='//button[@type="submit"][@id="product-addtocart-button"]'
success_msg='//div[@data-ui-id="message-success"]'