lnk_signIn = '(//a[contains(text(),"Sign In")])[1]'
txt_box_usrname='//input[@name="login[username]"]'
txt_box_password='//input[@name="login[password]"]'
btn_login='//button[@class="action login primary"]'
home_page_of_luman='//span[@class="logged-in"]'
# main_menu_xpath='//span[contains(text(),"Women")]'
menu_xpath='//span[contains(text(),<menu_option>)]'
women_page_of_luman='//span[contains(text(),"Women")][@class="base"]'
